# Generated by Django 5.0.4 on 2024-05-14 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='lesson_number',
            field=models.IntegerField(verbose_name='Dars Soni'),
        ),
    ]
