# Generated by Django 5.0.4 on 2024-05-15 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_product_videoid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='videoId',
            field=models.CharField(max_length=255, verbose_name='VideoId'),
        ),
    ]
