# Generated by Django 5.0.4 on 2024-05-30 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_product_videoid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='lesson_number',
            field=models.CharField(max_length=255, verbose_name='Dars Soni'),
        ),
    ]
